# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/guacamole/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),guacamole)

$(call add-radio-file-sha1-checked,radio/LOGO.img,1aebad420d5d3f21306b453e769196e78a50a06d)
$(call add-radio-file-sha1-checked,radio/abl.img,5ac258f6fac80751cb7d90602b6083ed7bad80e4)
$(call add-radio-file-sha1-checked,radio/aop.img,da737d5a1cc4073466cf6e45b0e5c3e3e7b6527a)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,a7c8dc46c52e9b8677d0c9f78c6f0dd2f381586d)
$(call add-radio-file-sha1-checked,radio/cmnlib.img,92d1f4f2da92c6c628ca54222323b311016db575)
$(call add-radio-file-sha1-checked,radio/cmnlib64.img,77021f2e11280a013cd2bf6529f2720c48f531f4)
$(call add-radio-file-sha1-checked,radio/devcfg.img,40902f7a1ab413640c517f25b6b167ed0488160f)
$(call add-radio-file-sha1-checked,radio/dsp.img,144b07528e20574fcb444aad5f6c906a20335b83)
$(call add-radio-file-sha1-checked,radio/hyp.img,4318c07431d65388cf342284931a06bd21c41fd4)
$(call add-radio-file-sha1-checked,radio/keymaster.img,114d05f46a83b2878e4b6293476cdcc9f6578d73)
$(call add-radio-file-sha1-checked,radio/modem.img,50d4e52ca1e1f662b8c650f1d1bc8b0fe5ef47e5)
$(call add-radio-file-sha1-checked,radio/qupfw.img,69d0a37f19f3e7db479808073036c465879ea5e8)
$(call add-radio-file-sha1-checked,radio/storsec.img,3adc90fb55ceec037ba65b2d61a032a431ec59c9)
$(call add-radio-file-sha1-checked,radio/tz.img,1d4aa692b130264150e9114d542cca41218d3387)
$(call add-radio-file-sha1-checked,radio/xbl.img,93ac3cb51f51aee7993633c56688220bec47b944)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,ed0ec5e07f6bfc5ef3da4ef2bdc82adc5364a4d8)

endif
